### ISSUE TITLE
isreadonly should return a boolean.

### ISSUE THREAD

**Issue by fsdfdfgdfghSD** [3skue/xAPI#1]
I've tried to open a pull request about this but its kinda confusing because of the comparing feature.

But this is the problem i want to point out.

isreadonly function from xAPI should return a **boolean** not a **{any} table**.

```lua
xAPI.AddGlobal({"isreadonly"}, function(self, t: {any}): boolean
	xAPI.TypeCheck(1, t, {"table"})

	local originalKey = t[1]

	local isNotFrozen = pcall(function()
		t[1] = 0
	end)

	if isNotFrozen or t[1] ~= originalKey then
		pcall(function()
			t[1] = originalKey
		end)

		return false
	end

	return true
end)
```

**Comment by 3skue** [comment]
I am going to fix this typo in the repo's source code.
However, since this is not a 'big' enough issue that won't affect runtime, this will not be replicated across releases (as of now).

When a new version comes out, I will be taking this into consideration though.
